apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-app
  labels:
    app: apache-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-app
  template:
    metadata:
      labels:
        app: apache-app
    spec:
      containers:
      - name: apache
        image: httpd:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: apache-html
          mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: apache-html
        configMap:
          name: apache-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-html
data:
  index.html: |
    <html>
    <head><title>Welcome to Apache!</title></head>
    <body>
      <h1>Hello from Apache HTTP Server on Kubernetes!</h1>
      <p>This is a sample page served by Apache.</p>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
spec:
  selector:
    app: apache-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
